locale: "en-US"
recordVideo: true
extensionModules:
  enable: true
  allowPowerFxNamespaces:
    - "Preview"  # Required for AssertJavaScript function
browserConfigurations:
  - browser: Chromium
powerFxTestTypes:
 - name: TextCollection
   value: |
      [{Value: Text}]
testFunctions:
 - description: Join lines of text with a semicolon
   code: |
    Join(lines: TextCollection): Text = Concat(lines, Value, ";")