locale: "en-US"
headless: false
recordVideo: true
extensionModules:
  enable: true
  allowPowerFxNamespaces:
    - "Preview"  # Required for AssertJavaScript function
browserConfigurations:
  - browser: Chromium
    channel: msedge
